"""teste delete column slug

Revision ID: 0c63707ab863
Revises: d552c045f658
Create Date: 2023-07-07 21:12:31.379152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c63707ab863'
down_revision = 'd552c045f658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
