"""fixed User model

Revision ID: 46d883683e4c
Revises: f0b9f75c3ed3
Create Date: 2023-08-09 16:19:10.791193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d883683e4c'
down_revision = 'f0b9f75c3ed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
