"""teste recriado column slug

Revision ID: 72c798424f1e
Revises: 0c63707ab863
Create Date: 2023-07-07 21:12:51.618103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c798424f1e'
down_revision = '0c63707ab863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
