"""fixed User model

Revision ID: f0b9f75c3ed3
Revises: 2f1580b388cd
Create Date: 2023-08-09 16:18:54.621512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b9f75c3ed3'
down_revision = '2f1580b388cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('User_name_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['username'])
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_name_key', 'User', ['name'])
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
